---
# if this is true the Knockback will only be applied to players but if it's false it will also apply to other entities
only-players: true
 
# this Knockback values will be applied to all the worlds that is not specified in "world-kb"
general-kb:
  horizontal: 0.4
  vertical: 0.4
  attack-speed: 10

# NOTE: "attack-speed" must be a whole number and must not include a decimal point
# FORMAT:
# 
# world-kb
#   worldname:
#     horizontal: 0.4
#     vertical: 0.4
#     attack-speed: 10
world-kb:
  worldNameExample:
    horizontal: 0.37
    vertical: 0.37
    attack-speed: 10
  anotherExample:
    horizontal: 0.25
    vertical: 0.25
    attack-speed: 2
...